### ISSUE TITLE
Sitecore 10.2 Support and Compatibility

### ISSUE THREAD

**Issue by maggon** [searchstax/searchstax-sitecore-plugin#30]

**Comment by SitecoreDave** [comment]
Pending in feature branch support-10-2

**Comment by maggon** [comment]
Confirmed with @SitecoreDave that this is completed

**Comment by maggon** [comment]
For consistency purposes, we should use 10.2.0 as opposed to 10.2. @SitecoreDave to fix the code, check in, make a new release and push the release.
