### ISSUE TITLE
Add Private Network Setting for Sitecore 10.0 and above

### ISSUE THREAD

**Issue by dkapoor** [searchstax/searchstax-sitecore-plugin#31]
As per https://doc.sitecore.com/en/developers/100/platform-administration-and-architecture/walkthrough--setting-up-solrcloud.html,

"If you only access nodes of SolrCloud within a private network, set the ContentSearch.IndexingManager.DisplayShortStatistic setting to true. This eliminates direct requests to the nodes used to display additional index statistics in the Indexing Manager Wizard."

Enhance the script to set this to true for SItecore versions 10.0 and above

**Comment by maggon** [comment]
This is completed as well.
