### ISSUE TITLE
Provide Commit Settings based on SearchStax recommendations

### ISSUE THREAD

**Issue by DiLascio** [searchstax/searchstax-sitecore-plugin#35]
It could either be

Two options being presented in the Yaml module and pros/cons listed in the plugin documentation
Option a) Use standard solr configs (-1 autoSoftCommit, 15000ms autoCommit)
Option b) Use SearchStax recommended configs (120000ms autoSoftCommit, 300000ms autoCommit)

Or simply using SearchStax recommended configs by default. This would provide a more sensible onboarding experience and reduce post-onboarding support tickets for performance issues and backup failures. 

SearchStax recommendations are here for reference - https://www.searchstax.com/blog/5-ways-to-optimize-your-solr-search-performance-for-sitecore/

**Comment by dkapoor** [comment]
Fixed in https://github.com/searchstax/searchstax-sitecore-plugin/releases/tag/v1.13
